services:
  - type: web
    name: yt-downloader
    runtime: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn backend.server:app --timeout 300 --workers 1"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
